Traceback (most recent call last):
  File "/scistor/ivm/mye500/projects/pg_risk_analysis/src/risk.py", line 517, in <module>
    save_risk = risk_output(sys.argv[1],sys.argv[2],sys.argv[3]) #country_code,hazard_type,infra_type
  File "/scistor/ivm/mye500/projects/pg_risk_analysis/src/risk.py", line 456, in risk_output
    line_risk,plant_risk,substation_risk = country_analysis_pg(country_code,hazard_type)
  File "/scistor/ivm/mye500/projects/pg_risk_analysis/src/risk.py", line 308, in country_analysis_pg
    pg_power_infra = extract_pg_infrastructure(country_code)
  File "/scistor/ivm/mye500/projects/pg_risk_analysis/src/extract.py", line 283, in extract_pg_infrastructure
    return pg_lines,pg_points
UnboundLocalError: local variable 'pg_points' referenced before assignment
